version: '3.8'

networks:
  main-net:
    external: true


services:

  prometheus:
    image: rundeck/rundeck:4.4.0
    container_name: some-rundeck
    deploy:
      replicas: 1
    ports:
      - 4440:4440
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

