version: '3.8'

services:

  jenkins:
    build: ./jenkins
    image: myjenkins
    container_name: jenkins
    deploy:
      replicas: 1
    ports:
      - '8080:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/jenkins_home
    environment:
      MY_VAR: myvar
    #restart: always

  agent-jnlp:
    build: ./agent-jnlp
    image: myagent-jnlp
    container_name: agent-jnlp
    deploy:
      replicas: 0
    ports:
      - '8022:22'
    volumes:
      - /var/jenkins_home
    environment:
      MY_VAR: myvar
    #restart: always

  agent-ssh:
    build: ./agent-ssh
    image: myagent-ssh
    container_name: agent-ssh
    deploy:
      replicas: 0
    ports:
      - '8022:22'
    volumes:
      - /var/jenkins_home
    environment:
      MY_VAR: myvar
    #restart: always