version: '3'

services:

  node1:
    build: ./master
    image: myjenkins
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/jenkins_home
    environment:
      MY_VAR: myvar
    #restart: always