jenkins:

  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  slaveAgentPort: 50000

  clouds:
  - docker:
      containerCap: 10
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://192.168.1.200:4243"
        readTimeout: 60
      exposeDockerHost: true
      name: "docker"
      templates:
      - connector:
          jnlp:
            jenkinsUrl: "http://192.168.1.200:8080"
            user: jenkins
            jnlpLauncher:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "192.168.1.200:5000/jnlp-linux-jkd11"
        instanceCapStr: "5"
        labelString: "linux doker jnlp jdk11"
        name: "jnlp-linux-jkd11"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        remoteFs: "/home/jenkins"
      - connector:
          jnlp:
            jenkinsUrl: "http://192.168.1.200:8080"
            user: jenkins
            jnlpLauncher:
              workDirSettings:
                disabled: false
                failIfWorkDirIsMissing: false
                internalDir: "remoting"
          dockerTemplateBase:
            cpuPeriod: 0
            cpuQuota: 0
            image: "192.168.1.200:5000/jnlp-linux-jkd8"
          instanceCapStr: "5"
          labelString: "linux doker jnlp jdk8"
          name: "jnlp-linux-jkd8"
          pullStrategy: PULL_ALWAYS
          pullTimeout: 300
          remoteFs: "/home/jenkins"
      - connector:
          ssh:
            sshKeyStrategy:
              injectSSHKey:
                user: "jenkins"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "192.168.1.200:5000/myagent-ssh"
        instanceCapStr: "5"
        labelString: "linux maven docker ssh jdk8"
        name: "ssh-agent"
        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        remoteFs: "/home/jenkins"
        nodeProperties:
          - envVars:
              env:
              - key: "JENKINS_AGENT_SSH_PUBKEY"
                value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEJpykWZv0JFqwfapv6TIpETY2C64BfoV4p8CjmEX4s8RJlBkyQYwWlzj8G1cts/A1JeppIrBPPtrROd6sTr4f1v8jgipVJta37wT68JhjZDMOViCxKApERgiDl94kiyidik3hbq9elFNjluhuWx/wrsX1uBuUWVdIv9x13DFeCEenAot4QnUYtg9wEg5VNe9v3E5BlOGFgEfGOg/xEeCOMohj8cKl+M3YX5vOYsJAyvS8CX6KQOZ3fQ3oRMdnQnzKJW4Tmtr7QEMNeiCfcNvKRHY77zdQYdOz7jW5NWbCHgayFDe8HqSP6BnZbiFsgJDqFRiNnGn3LnwYVvpvmqdr"
